<?php

/**
 * @file
 * Contains nestwatch_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nestwatch_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nestwatch_migrate module.
    case 'help.page.nestwatch_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for housing all NestWatch related migrations') . '</p>';
      return $output;

    default:
  }
}
