<?php

/**
 * @file
 * Contains nestwatch_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nestwatch_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nestwatch_views module.
    case 'help.page.nestwatch_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Additional Views settings for Nestwatch') . '</p>';
      return $output;

    default:
  }
}
