<?php

/**
 * @file
 * Contains nestwatch_entities.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nestwatch_entities_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nestwatch_entities module.
    case 'help.page.nestwatch_entities':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for managing all Nestwatch-related entities and data structures') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nestwatch_entities_theme() {
  return [
    'nestwatch_entities' => [
      'render element' => 'children',
    ],
  ];
}
